/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wolfdungeon3d;

import java.util.HashSet;

import com.jogamp.newt.opengl.GLWindow;

import processing.core.PApplet;
import processing.core.PVector;
import wolfdungeon3d.Game.GameState;

public class Runner extends PApplet {

	// State Handling
	Game game;
	RunnerState state = RunnerState.MENU;
	MainMenu mainMenu;
	int lastScore = -1;

	// Input Handling
	HashSet<Character> heldKeys = new HashSet<>();
	PVector mouseMovement = new PVector();
	PVector lastMousePosition = new PVector();

	static enum RunnerState {
		MENU, GAME, HELP, GAME_PAUSE
	}

	// State Handling //
	public void setState(RunnerState state) {
		this.state = state;
	}

	public RunnerState getState() {
		return state;
	}

	// Main update loop
	public void update() {
		switch (state) {
		case GAME:
			if (game == null) {
				game = new Game(this, (GLWindow) surface.getNative());
			} else {
				if (game.getState() != GameState.END) {
					for (Character k : heldKeys) {
						game.keyHeld(k);
					}
					game.update();
				} else {
					lastScore = game.calculateScore();
					state = RunnerState.MENU;
					game = null;
				}
			}
			break;
		default:
			break;
		}
	}

	////////////////////
	// Input Handling //
	////////////////////

	public void keyPressed() {
		if (!heldKeys.contains(key)) {
			heldKeys.add(key);
		}
		if (game != null) {
			game.keyPressed(key);
		}
	}

	public void keyReleased() {
		if (heldKeys.contains(key)) {
			heldKeys.remove(key);
		}
		if (game != null) {
			game.keyReleased(key);
		}
	}

	public void mouseClicked() {
		switch (state) {
		case MENU:
			mainMenu.handleOnClick(new PVector(mouseX, mouseY), new PVector(width, height));
			break;
		case GAME:
			if (game != null) {
				game.onClick();
			}
		default:
		}
	}

	///////////////////////
	// PApplet Functions //
	///////////////////////

	public void setup() {
		frameRate(60);
		Assets.createInstance(this);
		mainMenu = new MainMenu(this);
	}

	public void settings() {
		size(1920, 1080, PApplet.P3D);
		fullScreen();
	}

	public void draw() {
		update();
		background(0);
		switch (state) {
		case GAME:
			if (game != null)
				game.draw();
			break;
		case MENU:
			mainMenu.draw(this, new PVector(mouseX, mouseY), lastScore);
			break;
		default:
			break;
		}
	}

	public static void main(String[] args) {
		PApplet.main(new String[] { "wolfdungeon3d.Runner" });
	}
}
